/** @type {import('tailwindcss').Config} */
export default {
  content: ['./index.html', './src/**/*.{js,jsx}'],
  darkMode: 'class',
  theme: {
    extend: {
      colors: {
        'surface-variant': '#dadddf',
        'tertiary-fixed': '#eb9bfe',
        'on-tertiary-fixed-variant': '#651d79',
        'secondary-dim': '#4a5156',
        'on-secondary-container': '#4c5358',
        'on-primary': '#ffefeb',
        'surface-container-high': '#e0e3e4',
        'inverse-on-surface': '#9b9d9e',
        'on-secondary-fixed-variant': '#555c62',
        'inverse-surface': '#0c0f10',
        'inverse-primary': '#ff5717',
        'surface-container-low': '#eff1f2',
        'error-container': '#fb5151',
        'on-error': '#ffefee',
        outline: '#757778',
        'on-secondary-fixed': '#394045',
        'tertiary-fixed-dim': '#dd8eef',
        secondary: '#555c62',
        error: '#b31b25',
        'secondary-fixed-dim': '#ced5db',
        'primary-dim': '#942a00',
        'tertiary-dim': '#77308b',
        'primary-fixed-dim': '#ff5d23',
        'surface-tint': '#a83100',
        'on-background': '#2c2f30',
        'primary-container': '#ff784c',
        'secondary-fixed': '#dde3e9',
        'surface-container-highest': '#dadddf',
        'on-primary-container': '#460f00',
        primary: '#a83100',
        tertiary: '#843d98',
        'tertiary-container': '#eb9bfe',
        'secondary-container': '#dde3e9',
        'on-secondary': '#edf3fa',
        'error-dim': '#9f0519',
        background: '#f5f6f7',
        surface: '#f5f6f7',
        'on-error-container': '#570008',
        'surface-container-lowest': '#ffffff',
        'on-tertiary-fixed': '#3b004c',
        'outline-variant': '#abadae',
        'surface-bright': '#f5f6f7',
        'on-primary-fixed-variant': '#561500',
        'surface-container': '#e6e8ea',
        'on-primary-fixed': '#000000',
        'on-surface': '#2c2f30',
        'on-tertiary-container': '#5b1170',
        'surface-dim': '#d1d5d7',
        'primary-fixed': '#ff784c',
        'on-tertiary': '#ffeefd',
        'on-surface-variant': '#595c5d',
      },
      borderRadius: {
        DEFAULT: '1rem',
        lg: '2rem',
        xl: '3rem',
        full: '9999px',
      },
      fontFamily: {
        headline: ['"Plus Jakarta Sans"', 'sans-serif'],
        body: ['Inter', 'sans-serif'],
        label: ['Inter', 'sans-serif'],
      },
    },
  },
  plugins: [],
}
